name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
    name: Test on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - uses: actions/upload-artifact@v2
        with:
          name: e2e-nyc-output
          path: '.nyc_output'
        if: ${{ always() }}
      - run: npm run bundle
      - run: npm run test

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: logs
      #     path: logs
      #   if: ${{ always() }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: cypress
      #     path: cypress
      #   if: ${{ always() }}
