name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: npx cypress install
      - run: pnpm lint:css
      - run: pnpm build
      - run: pnpm compile-scss
      - run: pnpm test

      - name: Upload coverage report on to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
