name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: pnpm

      - name: Install
        run: npm install
      - name: Install Cypress
        run: npx cypress install

      - name: Lint TS
        run: npm run lint:ts
      - name: Lint CSS
        run: npm run lint:css
      - name: Check TS
        run: npm run check:ts

      - name: Build JS
        run: npm run build-vite
      - name: Build CSS
        run: npm run compile-scss
      - name: Copy CSS
        run: npm run copy-css-cp
      - name: Copy JS
        run: npm run docs

      - name: Clean coverage
        run: npm run clean-coverage
      - name: Run tests
        run: npx cypress run

      - name: Upload coverage report on to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
